// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://migiylavnrplbqiisgth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZ2l5bGF2bnJwbGJxaWlzZ3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODUzMjAsImV4cCI6MjA2NTg2MTMyMH0.s3buJnaJMLoR6YljlSL5a59cfYHFUtR3XAKRiKLe8Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);